"AAPL": "Apple"
"MSFT": "Microsoft"
"2222_SR": "Saudi Arabian Oil Company|Aramc|2222_SR"
"GOOGL": "Google"
"AMZN": "Amazon"
"NVDA": "NVidia"
"META": "Meta|Facebook"
"TSLA": "Tesla"
"LLY": "Eli Lilly"
"WMT": "Walmart"